from django.urls import path
from . import views

urlpatterns = [
    path("health", views.health),
    path("site", views.site),
    path("auth/register", views.register),
    path("auth/login", views.login),
    path("auth/me", views.me),
    path("categories", views.categories),
    path("categories/<str:slug>", views.category_detail),
    path("products", views.products),
    path("products/brands", views.brands),
    path("products/slug/<str:slug>", views.product_by_slug),
    path("products/<int:product_id>", views.product_detail),
    path("cart", views.cart),
    path("cart/<int:item_id>", views.cart_item),
    path("wishlist", views.wishlist),
    path("wishlist/product/<int:product_id>", views.wishlist_by_product),
    path("wishlist/<int:item_id>", views.wishlist_item),
    path("orders", views.orders),
    path("orders/<int:order_id>", views.order_detail),
    path("admin/stats", views.admin_stats),
    path("admin/categories", views.admin_categories),
    path("admin/categories/<int:category_id>", views.admin_category_detail),
    path("admin/products", views.admin_products),
    path("admin/products/<int:product_id>", views.admin_product_detail),
    path("admin/orders", views.admin_orders),
    path("admin/orders/<int:order_id>", views.admin_order_status),
    path("admin/orders/<int:order_id>/payment", views.admin_order_payment),
    path("admin/payments", views.admin_payments),
    path("admin/users", views.admin_users),
    path("admin/users/<int:user_id>", views.admin_user_detail),
    path("admin/settings", views.admin_settings),
]
